#pragma once

//  Generated by CMake's configure_file():
//      refers .in file to fix.
#define NE_BUILD_DATE       "12-07 2017"
#define NE_BUILD_TIME       "00:28:02"
#define NE_VERSION_MAJOR    0
#define NE_VERSION_MINOR    0
#define NE_VERSION_FIX      1
#define NE_VERSION_VALUE    "0.0.1"
