#pragma once

//  Generated by CMake's configure_file():
//      refers .in file to fix.
#define NE_BUILD_DATE       "08-07 2017"
#define NE_BUILD_TIME       "02:13:10"
#define NE_VERSION_MAJOR    0
#define NE_VERSION_MINOR    0
#define NE_VERSION_FIX      1
#define NE_VERSION_VALUE    "0.0.1"
