enum ErrorCode
{
	UNDEFINED = 0,
	NEMODULE_IS_NOT_VALID,
	MODULESET_IS_NOT_VALID,
	DLL_HEADERSET_IS_NOT_VALID,
	INVALID_DLL_PATH,
	DLL_PATH_IS_NULLED,
	FAILED_TO_ACCESS_DLL,
	FAILED_TO_ACCESS_ENTRY_POINT,
	END_OF_ERROR_CODE
};