#define _DEFAULT_WIDTH_RATE						0.5
#define _DEFAULT_HEIGHT_RATE					0.5
#define _FINAL_RENDER_TARGET_OUTPUT				0
#define _FINAL_RENDER_TARGET_NEW_BUFFER			1
#define _FINAL_RENDER_TARGET_PREVIOUS_BUFFER	2
#define _RENDER_TARGET_VERTEX_FVF				(D3DFVF_XYZ | D3DFVF_DIFFUSE | D3DFVF_TEX1)
