#define DEFAULT_CCARTRIDGEHEADER_VALID_CODE			0x4A7C
#define DEFAULT_CCARTRIDGEHEADER_VERSION			1
#define DEFAULT_CCARTRIDGEHEADER_ALGORITHM_NUMBER	1
#define DEFAULT_CCARTRIDGEHEADER_COMPRESSED			false
