#pragma once

#include "exprs/getExpr.hpp"
#include "exprs/runExpr.hpp"
#include "exprs/blockExpr.hpp"
#include "exprs/exprMaker.hpp"
#include "exprs/defVarExpr.hpp"
#include "exprs/returnExpr.hpp"
#include "exprs/assignExpr.hpp"
#include "exprs/defAssignExpr.hpp"
#include "exprs/asExpr.hpp"
#include "exprs/FAOExpr.hpp"
#include "exprs/makeExpr.hpp"
#include "exprs/getGenericExpr.hpp"
#include "exprs/defSeqExpr.hpp"
