name: CI for main

on:
  push:
    branches: [ test-workflow ]
  pull_request:
    branches: [ test-workflow ]

jobs:
  checking-code-format:
    name: check code format with clang-format
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        path:
          - check: 'mod'
            exclude: '(leafLowparser|leafLowscanner|lowparser|lowscanner)'
    steps:
    - name: checkout repository codes
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: test-workflow

    - name: Install clang-format-18
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" | sudo tee /etc/apt/sources.list.d/llvm.list
        sudo apt update
        sudo apt install -y clang-format-18

    - name: run formatter 
      run: |
        cd ${{github.workspace}} 
        python3 build/builder.py format

    - name: check that there is a change
      run: |
        git diff > output.txt
        if [ ! -s output.txt ]; then
          echo "error: some codes violates our code style."
          cat output.txt
          exit 1
        fi
