name: CI for main

on:
  push:
    branches: [ test-workflow ]
  pull_request:
    branches: [ test-workflow ]

jobs:
  checking-code-format:
    name: check code format with clang-format
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        path:
          - check: 'mod'
            exclude: '(leafLowparser|leafLowscanner|lowparser|lowscanner)'
    steps:
    - name: checkout repository codes
      uses: actions/checkout@v4

    - name: Install clang-format-18
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" | sudo tee /etc/apt/sources.list.d/llvm.list
        sudo apt update
        sudo apt install -y clang-format-18

    - name: run clang-format
      run: |
        git clang-format-18 --diff --binary clang-format-18 HEAD^ --extensions c,cpp,h,hpp,inl > clang-format.diff

    - name: check formatting
      run: |
        if [ -s clang-format.diff ]; then
          echo "error: clang-format check failure."
          cat clang-format.diff
          exit 1
        fi
